import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, ExternalLink, Search, Sparkles } from 'lucide-react';
import { Link, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { ENTRIES, HERO_IMAGES, type Entry } from './skills/data';

const reactions: Record<Entry['personality'], string[]> = {
  bold: ['镜头就位，准备开拍。', '别眨眼，下一帧更精彩。'],
  calm: ['我已经把流程整理好了。', '慢一点，细节会自己出现。'],
  playful: ['被你发现啦。', '今天要不要试个新状态？'],
  warm: ['来，跟我一起把故事讲出来。', '收到你的眼神了。'],
  precise: ['参数锁定，开始工作。', '每一格都值得核对。'],
};

function Avatar({ item, className = '' }: { item: Entry; className?: string }) {
  return <span className={`avatar avatar--${item.personality} ${className}`}><img src={item.avatar} alt="" draggable={false} /><i /></span>;
}

function Hero({ open }: { open: (entry: Entry) => void }) {
  const [activeIndex, setActiveIndex] = useState(0); const [animating, setAnimating] = useState(false); const [mobile, setMobile] = useState(false); const [reaction, setReaction] = useState('点击我，看看我会怎么回应。');
  const active = ENTRIES[activeIndex];
  useEffect(() => { HERO_IMAGES.forEach(({ src }) => { const image = new Image(); image.src = src; }); const resize = () => setMobile(window.innerWidth < 640); resize(); window.addEventListener('resize', resize); return () => window.removeEventListener('resize', resize); }, []);
  const move = (dir: 'next' | 'prev') => { if (animating) return; setAnimating(true); setActiveIndex((value) => dir === 'next' ? (value + 1) % ENTRIES.length : (value + ENTRIES.length - 1) % ENTRIES.length); window.setTimeout(() => setAnimating(false), 650); };
  const visibleEntries = [active, ENTRIES[(activeIndex + ENTRIES.length - 1) % ENTRIES.length], ENTRIES[(activeIndex + 1) % ENTRIES.length], ENTRIES[(activeIndex + 2) % ENTRIES.length]];
  const role = (index: number) => ['center', 'left', 'right', 'back'][index];
  const respond = () => { const lines = reactions[active.personality]; setReaction(lines[Math.floor(Math.random() * lines.length)]); };
  return <section className="hero" style={{ backgroundColor: HERO_IMAGES[activeIndex % 4].bg }}><div className="hero__stage"><div className="hero__grain" /><div className="hero__ghost">3D SHAPE</div><div className="hero__brand">TOONHUB / SKILL ATLAS</div><div className="hero__intro"><span className="eyebrow">PERSONA LIBRARY · {ENTRIES.length} CHARACTERS</span><h1>每个 skill，<br /><em>都有自己的性格。</em></h1><p>点击让角色回应，双击进入完整档案。把你的工作流，变成一群会陪你工作的 3D 小人。</p></div><div className="hero__carousel">{HERO_IMAGES.map((image, index) => <button type="button" key={`${image.src}-${index}`} className={`figurine figurine--${role(index)}`} style={{ backgroundColor: image.panel }} onClick={respond} onDoubleClick={() => open(visibleEntries[index])} aria-label={`${visibleEntries[index].name}，点击互动，双击查看详情`}><img src={image.src} alt="" draggable={false} /></button>)}</div><div className="hero__speech" aria-live="polite"><Sparkles size={15} /> {reaction}</div><div className="hero__meta"><div><p className="hero__title">{active.name}</p><p className="hero__caption">{active.summary}</p></div><div className="hero__controls"><button type="button" onClick={() => move('prev')} aria-label="上一个角色"><ArrowLeft size={22} /></button><button type="button" onClick={() => move('next')} aria-label="下一个角色"><ArrowRight size={22} /></button></div></div><div className="hero__roster" aria-label="首屏角色快速选择">{ENTRIES.map((entry, index) => <button type="button" key={entry.slug} className={index === activeIndex ? 'active' : ''} onClick={() => setActiveIndex(index)} aria-label={`切换到 ${entry.name}`}><img src={entry.avatar} alt="" /><span>{entry.name}</span></button>)}</div><button type="button" className="hero__discover" onClick={() => open(active)}>DISCOVER IT <ArrowRight size={22} /></button><div className="hero__hint">{mobile ? '点击互动 · 双击查看' : 'CLICK TO INTERACT · DOUBLE-CLICK TO OPEN'}</div></div></section>;
}

function Card({ entry, open }: { entry: Entry; open: (entry: Entry) => void }) { return <button type="button" className="entry-card" onClick={() => open(entry)}><Avatar item={entry} /><span className="entry-card__body"><span className="entry-card__top"><span>{entry.kind === 'skill' ? 'SKILL' : 'SITE'}</span><span>v{entry.version}</span></span><strong>{entry.name}</strong><span>{entry.summary}</span><span className="tags">{entry.tags.map((tag) => <i key={tag}>{tag}</i>)}</span></span><ArrowRight size={18} className="entry-card__arrow" /></button>; }

function Library() { const navigate = useNavigate(); const [query, setQuery] = useState(''); const [kind, setKind] = useState<'all' | 'skill' | 'site'>('all'); const filtered = useMemo(() => ENTRIES.filter((entry) => (kind === 'all' || entry.kind === kind) && `${entry.name} ${entry.summary} ${entry.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [kind, query]); return <main><Hero open={(entry) => navigate(`/skills/${entry.slug}`)} /><section className="library"><header className="library__header"><div><span className="eyebrow">THE ATLAS</span><h2>技能与网站角色库</h2><p>公开展示当前有效的工作流。完整内容保留在每个角色的档案里。</p></div><span className="library__count">{String(filtered.length).padStart(2, '0')} ENTRIES</span></header><div className="toolbar"><label><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索 skill、网站或标签" /></label><div className="filters">{(['all','skill','site'] as const).map((value) => <button type="button" key={value} className={kind === value ? 'active' : ''} onClick={() => setKind(value)}>{value === 'all' ? '全部' : value === 'skill' ? 'Skills' : 'Sites'}</button>)}</div></div><div className="entry-grid">{filtered.map((entry) => <Card key={entry.slug} entry={entry} open={(item) => navigate(`/skills/${item.slug}`)} />)}</div></section></main>; }

function Detail() { const { slug } = useParams(); const navigate = useNavigate(); const entry = ENTRIES.find((item) => item.slug === slug); const [content, setContent] = useState('正在读取完整内容…'); useEffect(() => { if (!entry) return; fetch(entry.contentPath).then((response) => response.ok ? response.text() : Promise.reject()).then(setContent).catch(() => setContent('暂未找到公开内容文件。请先在本地同步脚本中导入该 Markdown。')); }, [entry]); if (!entry) return <main className="empty"><h1>找不到这个角色</h1><button type="button" onClick={() => navigate('/')}>返回角色库</button></main>; return <main className="detail"><header className="detail__nav"><button type="button" onClick={() => navigate('/')}><ArrowLeft size={18} /> 返回角色库</button><span>{entry.kind === 'skill' ? 'SKILL PROFILE' : 'SITE PROFILE'}</span></header><section className="detail__hero"><Avatar item={entry} className="detail__avatar" /><div><span className="eyebrow">{entry.name}</span><h1>{entry.name}</h1><p>{entry.summary}</p><div className="chips">{entry.scenarios.map((scenario) => <span key={scenario}>{scenario}</span>)}</div></div>{entry.externalUrl && <a href={entry.externalUrl} target="_blank" rel="noreferrer" className="external">打开网站 <ExternalLink size={16} /></a>}</section><section className="detail__content"><div className="detail__content-head"><div><span className="eyebrow">FULL CONTENT</span><h2>完整 Markdown</h2></div><span>VERSION {entry.version} · UPDATED {entry.updated}</span></div><pre>{content}</pre></section></main>; }

export default function App() { return <Routes><Route path="/" element={<Library />} /><Route path="/skills/:slug" element={<Detail />} /></Routes>; }
